apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: [ "sleep" ]          # same as in dockerfile for ENTRYPOINT[ "sleep" ]
    # command: [ "value1", "value2" ]
      args: [ "10" ]                   # same as in dockerfile for CMD[ "10" ]
