apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: app-config-volume
          mountPath: /etc/config
  volumes:
    - name: app-config-volume
      configMap:
        name: app-config


# When we create configmap as a volume, so each configmap Key Value becomes a file inside the configmap Mount path.
# ls /etc/config/
# APP_COLOR  APP_MODE
# cat /etc/config/APP_COLOR       => blue
# cat /etc/config/APP_MODE        => prod

# Inside pod container to find configmap as mounted point
# df -aTh | grep "config"