apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - port: 80          # port on service
      targetPort: 80    # port on Pod
  selector:
    app: myapp
    type: back-end