apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80   # port where backend pod is access
  selector:
    app: myapp
    type: back-end