apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80   # port on pod
     port: 80         # port on service
     nodePort: 30004  # port on node 
  selector:
    app: myapp