apiVersion: v1
kind: Pod
metadata: 
  name: web-pod
spec:
  securityContext:                  # security context at pod level (applicable to all containers in that pod)
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command: [ "sleep", "3600" ]    