apiVersion: v1
kind: Pod
metadata: 
  name: web-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: [ "sleep", "3600" ]    
      securityContext:                  # security context at container level 
        runAsUser: 1000
        capibilities: 
          add: ["MAC_ADMIN"]    
    
# Note:
# Capibilities are only supported at the container level and not at th pod level 